### ISSUE TITLE
current version?

### ISSUE THREAD

**Issue by zzyzzyzzx** [mreschke/mrcore-modules-wiki#1]
does this currently work with laravel 5.4 i think it is? the newest version

**Comment by mreschke** [comment]
untested. only tested with 5.3 so far, but I'll update soon

**Comment by zzyzzyzzx** [comment]
do you have maybe a rough ETA or something? im pretty sure i can just jump back if need be, was just trying to avoid it

**Comment by zzyzzyzzx** [comment]
found a different wiki since it looks dead

**Comment by mreschke** [comment]
It is not dead, it is used daily on a constant basis, but stable on L5.3 at the moment. This is a dedicated enterprise project for several companies.  Feel free to use it of course, but it will not be upgraded to L5.4 for awhile.
